---
- name: Install cisagov/cyhy-core
  ansible.builtin.include_role:
    name: cyhy_core
  vars:
    cyhy_core_maxmind_license_key: "{{ cyhy_reports_maxmind_license_key }}"

- name: Install cisagov/ncats-webd
  ansible.builtin.include_role:
    name: ncats_webd
  vars:
    ncats_webd_maxmind_license_key: "{{ cyhy_reports_maxmind_license_key }}"

- name: Install and configure TeX Live
  ansible.builtin.include_tasks: install_and_configure_texlive.yml

#
# Install cyhy-reports
#

# The Python dependencies are from here:
# https://github.com/cisagov/cyhy-reports/blob/develop/setup.py#L50-L71
#
# I'd prefer to install the Python dependencies via pip, but then I
# get errors about modules being built with a different version of
# numpy than what is on the host.  Doing it this way seems to work
# much better.
- name: Install cyhy-reports dependencies
  ansible.builtin.package:
    name:
      - python-dateutil
      - python-docopt
      - python-mpltoolkits.basemap
      - python-netaddr
      - python-numpy
      - python-pandas
      - python-progressbar
      - python-pypdf2
      - python-unicodecsv

- name: Install the cyhy-reports package
  ansible.builtin.pip:
    executable: /usr/bin/pip2
    name: https://api.github.com/repos/cisagov/cyhy-reports/tarball/develop

#
# Download the cyhy-reports code for some extra content we need
#

- name: Create the directories we need for cyhy-reports
  ansible.builtin.file:
    group: "{{ cyhy_reports_file_owner_group | default(omit) }}"
    mode: 0755
    owner: "{{ cyhy_reports_file_owner_username | default(omit) }}"
    path: "{{ item }}"
    state: directory
  loop:
    - /var/cyhy/reports
    - /var/cyhy/reports/output
    - /var/local/cyhy/reports

- name: Download and untar the cyhy-reports tarball
  ansible.builtin.unarchive:
    dest: /var/local/cyhy/reports
    extra_opts:
      - "--strip-components=1"
    group: "{{ cyhy_reports_file_owner_group | default(omit) }}"
    owner: "{{ cyhy_reports_file_owner_username | default(omit) }}"
    remote_src: yes
    src: https://api.github.com/repos/cisagov/cyhy-reports/tarball/develop

- name: Copy the reporting and notification scripts
  ansible.builtin.copy:
    dest: /var/cyhy/reports/{{ item }}
    group: "{{ cyhy_reports_file_owner_group | default(omit) }}"
    mode: 0755
    owner: "{{ cyhy_reports_file_owner_username | default(omit) }}"
    remote_src: yes
    src: /var/local/cyhy/reports/extras/{{ item }}
  loop:
    - create_send_notifications.py
    - create_snapshots_reports_scorecard.py

# rsync is required by the synchronize module
- name: Install rsync
  ansible.builtin.package:
    name: rsync

- name: Copy the cyhy-reports fonts
  ansible.posix.synchronize:
    dest: /usr/local/share/fonts
    src: /var/local/cyhy/reports/cyhy_report/assets/Fonts/
  delegate_to: "{{ inventory_hostname }}"
  register: sync_output
  notify:
    - Install the cyhy-reports fonts
