---
# tasks file for cyhy_reports

#
# Grab the cyhy-reports code
#
- name: Create the /var/local/cyhy/reports directory
  file:
    path: /var/local/cyhy/reports
    state: directory

- name: Download and untar the cyhy-reports tarball
  unarchive:
    # TODO revert back to develop when done testing
    src: "https://api.github.com/repos/jsf9k/cyhy-reports/tarball/improvement/cyhy_notifications?\
    access_token={{ github_oauth_token }}"
    dest: /var/local/cyhy/reports
    remote_src: yes
    extra_opts:
      - "--strip-components=1"

#
# Install cyhy-reports
#

# These dependencies are from here:
# https://github.com/jsf9k/cal-overlay/blob/develop/net-analyzer/cyhy-reports/cyhy-reports-1.0.12.ebuild#L31-L49
#
# I'd prefer to install the python dependencies via pip, but then I
# get errors about modules being built with a different version of
# numpy than what is on the host.  Doing it this way seems to work
# much better.
- name: Install cyhy-reports dependencies
  package:
    name:
      - python-mpltoolkits.basemap
      - python-numpy
      - python-dateutil
      - python-netaddr
      - python-pystache
      - python-pandas
      - python-progressbar
      - python-docopt
      - python-unicodecsv
      - python-pypdf2
      - texlive
      - texlive-fonts-extra
      - texlive-latex-extra
      - texlive-science
      - texlive-xetex

- name: Install cyhy-reports
  pip:
    name: file:///var/local/cyhy/reports

- name: Create some directories that cyhy-reports requires
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /var/cyhy/reports
    - /var/cyhy/reports/output
    - /var/cyhy/notifications
    - /var/cyhy/notifications/output

- name: Copy the reporting and notification scripts
  copy:
    src: "/var/local/cyhy/reports/extras/{{ item }}"
    dest: "/var/cyhy/reports/{{ item }}"
    mode: 0755
    remote_src: yes
  loop:
    - create_snapshots_reports_scorecard.py
    - create_send_notifications.py

# rsync is required by synchronize
- name: Install rsync
  package:
    name: rsync

- name: Copy the cyhy-reports fonts
  synchronize:
    src: /var/local/cyhy/reports/cyhy_report/assets/Fonts/
    dest: /usr/local/share/fonts
  delegate_to: "{{ inventory_hostname }}"
  register: sync_output
  notify:
    - Install the cyhy-reports fonts
