---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: debian9
    image: debian:stretch-slim
provisioner:
  name: ansible
  config_options:
    defaults:
      # The OS family and distribution for Kali is "Kali GNU/Linux",
      # which is not an allowable group name in Ansible due to the
      # space and the slash.  This option converts those characters to
      # underscores when creating the group name.
      force_valid_group_names: always
scenario:
  name: default
verifier:
  name: testinfra
