---
- hosts: all
  name: Install pip3/python3 and remove pip2/python2
  become: yes
  become_method: sudo
  roles:
    - role: pip
      vars:
        install_pip2: true
    - role: python
      vars:
        install_python2: true
